"""Editorial content for role-specific resume guides.

Every entry supplies real role context so generated pages do not differ only by
the job title. Example metrics and bullets are writing patterns, not claims a
visitor should copy without replacing the facts.
"""


def role(industry, title, intro, summary, skills, priorities, metrics, bullets, mistakes, credentials, templates):
    return {
        "industry": industry,
        "role": title,
        "intro": intro,
        "summary": summary,
        "skills": skills,
        "priorities": priorities,
        "metrics": metrics,
        "bullets": bullets,
        "mistakes": mistakes,
        "credentials": credentials,
        "templates": templates,
    }


ROLE_GUIDES = {
    "software-engineer": role(
        "Technology", "Software Engineer",
        "A software engineer resume should show what you built, the technical decisions you owned, and how the software performed in production. Name the stack, scale, constraints, and outcome instead of listing technologies without context.",
        "Software engineer with 6 years of experience building customer-facing SaaS products in Python, TypeScript, and AWS. Led service reliability and deployment improvements that reduced API latency by 38% and shortened release cycles from weekly to daily.",
        ["Python", "TypeScript", "System design", "APIs", "SQL", "AWS", "Automated testing", "CI/CD"],
        ["Production ownership", "Technical depth", "System scale", "Cross-functional delivery"],
        [("Performance", "latency, throughput, error rate, or page speed"), ("Delivery", "deployment frequency, lead time, or cycle time"), ("Reliability", "uptime, incident volume, recovery time, or test coverage")],
        ["Reduced API latency by 38% by redesigning caching and database access patterns.", "Led migration of twelve services to automated deployment with zero planned downtime.", "Raised critical-path test coverage from 61% to 89% and cut regression incidents.", "Partnered with product and design to ship an onboarding flow used by 48,000 monthly users."],
        ["A tool list with no evidence of use", "Project bullets that omit scale or your contribution", "Dense architecture jargon a recruiter cannot scan", "Claiming team outcomes without clarifying ownership"],
        "Put a computer science degree near the top only when you are early in your career. Experienced engineers should lead with work. Add cloud, security, or platform certifications only when the target job values them.",
        ["template-029", "template-004", "template-018"],
    ),
    "product-manager": role(
        "Product and Program Management", "Product Manager",
        "A product manager resume needs a clear record of customer insight, prioritization, and business results. Show the problem you chose, the tradeoff you made, and the measurable change after launch.",
        "B2B product manager with 7 years of experience across discovery, roadmap strategy, and enterprise SaaS launches. Turned customer research and usage data into onboarding changes that lifted activation by 17% over two quarters.",
        ["Product strategy", "Roadmapping", "User research", "Analytics", "Experimentation", "Go-to-market", "Stakeholder alignment", "Agile delivery"],
        ["Problem selection", "Decision quality", "Business impact", "Leadership without authority"],
        [("Adoption", "activation, engagement, retention, or feature usage"), ("Commercial", "revenue, pipeline, expansion, or conversion"), ("Execution", "cycle time, predictability, or launch scope")],
        ["Defined an onboarding roadmap that increased activation by 17% over two quarters.", "Synthesized forty customer interviews into a prioritized enterprise feature plan.", "Reframed packaging using win-loss analysis, contributing to a 12% increase in expansion revenue.", "Aligned design, engineering, sales, and support around measurable quarterly outcomes."],
        ["Describing ceremonies instead of decisions", "Listing features without customer or business outcomes", "Using vague ownership words such as helped or supported", "Overloading the resume with product terminology"],
        "A business, technical, or design degree can add context but is not the headline for an experienced PM. Include product certifications only when they reflect how you actually work.",
        ["template-015", "template-011", "template-020"],
    ),
    "project-manager": role(
        "Product and Program Management", "Project Manager",
        "A project manager resume should prove that you can control scope, dependencies, risk, budget, and communication. Name the program size and explain how your actions protected the outcome.",
        "Project manager with 8 years of experience delivering technology and operations programs across distributed teams. Managed portfolios up to $1.8M and introduced risk reviews that reduced late milestone changes by 31%.",
        ["Project planning", "Risk management", "Budget control", "Vendor management", "Change control", "Resource planning", "Executive reporting", "Jira"],
        ["Delivery record", "Risk judgment", "Commercial control", "Stakeholder communication"],
        [("Schedule", "days saved, on-time rate, or milestone predictability"), ("Budget", "portfolio value, variance, or cost avoided"), ("Complexity", "teams, vendors, regions, or workstreams coordinated")],
        ["Delivered a multi-region platform rollout three weeks ahead of schedule.", "Introduced risk reviews that reduced late milestone changes by 31%.", "Managed a $1.8M program across four vendors and six internal teams.", "Recovered a delayed workstream by renegotiating dependencies and resequencing the critical path."],
        ["A long list of project tools", "No indication of budget or project scale", "Reporting status without showing intervention", "Treating every project as equally important"],
        "Place PMP, PRINCE2, Scrum, or sector-specific credentials beside your name or in a certifications section when the posting requests them. Do not let certifications replace delivery evidence.",
        ["template-016", "template-011", "template-029"],
    ),
    "data-analyst": role(
        "Technology", "Data Analyst",
        "A data analyst resume should connect technical analysis with a decision. Explain the question, data source, method, and change your work enabled rather than presenting dashboards as the final outcome.",
        "Data analyst with 4 years of experience using SQL, Python, and Tableau to improve product and commercial decisions. Automated recurring reporting and identified checkout friction that informed a change worth 9% more conversions.",
        ["SQL", "Python", "Tableau", "Power BI", "Experiment analysis", "Forecasting", "Data modeling", "Data quality"],
        ["Analytical reasoning", "Reliable data", "Decision support", "Communication"],
        [("Efficiency", "hours saved or reporting cycle reduced"), ("Quality", "error rate, coverage, or reconciliation accuracy"), ("Business result", "conversion, retention, cost, or forecast accuracy")],
        ["Built a retention dashboard used in weekly decisions by five product teams.", "Identified checkout friction that informed a change worth 9% more conversions.", "Automated recurring reporting and saved analysts twenty hours each month.", "Reconciled three source systems and raised metric agreement from 86% to 99%."],
        ["Naming charts without the decision they supported", "Listing every library you have tried", "Ignoring data validation and quality work", "Using unexplained statistical terminology"],
        "Include a relevant degree when it helps establish quantitative training. Projects are valuable for early-career analysts when they state the dataset, method, result, and limitation.",
        ["template-017", "template-026", "template-029"],
    ),
    "accountant": role(
        "Finance", "Accountant",
        "An accountant resume should communicate accuracy, control, reporting scope, and close performance. Specify the entities, accounts, standards, and systems you handled, then show how you improved reliability or speed.",
        "Accountant with 6 years of experience in multi-entity reporting, reconciliations, and month-end close. Shortened close from eight business days to five while strengthening expense controls across three business units.",
        ["Financial reporting", "Reconciliation", "Month-end close", "General ledger", "GAAP", "Tax compliance", "Internal controls", "ERP systems"],
        ["Accuracy", "Control discipline", "Reporting scope", "Process improvement"],
        [("Close", "days to close or on-time reporting rate"), ("Scope", "entities, accounts, currencies, or transaction volume"), ("Control", "exceptions resolved, audit findings, or error reduction")],
        ["Shortened month-end close from eight business days to five.", "Reconciled 140 accounts and resolved a six-figure historical discrepancy.", "Standardized expense controls across three business units.", "Prepared audit schedules that reduced follow-up requests by 25%."],
        ["Generic duties copied from the job description", "No accounting standard or entity context", "Omitting systems used in core workflows", "Reporting confidential figures without permission"],
        "List CPA, ACCA, CMA, or local licensure prominently when active. State progress accurately if you are still completing exams. Education matters more for entry-level candidates than for experienced accountants.",
        ["template-013", "template-004", "template-018"],
    ),
    "financial-analyst": role(
        "Finance", "Financial Analyst",
        "A financial analyst resume should show how your models and analysis changed a plan, investment, forecast, or operating decision. State the business question and who used the recommendation.",
        "Financial analyst with 5 years of FP&A and investment modeling experience. Built scenarios that guided a $4M capacity decision and improved quarterly forecast accuracy by 12 percentage points.",
        ["Financial modeling", "Forecasting", "Variance analysis", "Scenario planning", "Excel", "SQL", "Business partnering", "Executive presentations"],
        ["Model integrity", "Commercial judgment", "Forecast accuracy", "Executive communication"],
        [("Forecast", "accuracy, bias, or planning cycle time"), ("Decision", "investment value, savings, or revenue protected"), ("Coverage", "business units, cost centers, or markets analyzed")],
        ["Built a scenario model that guided a $4M capacity investment.", "Improved quarterly forecast accuracy by 12 percentage points.", "Translated operating variances into actions for regional leaders.", "Automated monthly reporting across 24 cost centers and saved two days per cycle."],
        ["Claiming advanced Excel with no model example", "Presenting analysis without its decision", "Using finance acronyms outside their context", "Listing every report as a separate achievement"],
        "CFA progress, accounting credentials, or sector qualifications can help when relevant. Give models and decision support more space than coursework after your first substantial role.",
        ["template-017", "template-016", "template-026"],
    ),
    "marketing-manager": role(
        "Marketing and Sales", "Marketing Manager",
        "A marketing manager resume should connect audience strategy and execution with pipeline, revenue, retention, or brand outcomes. Separate channel activity from the commercial result it produced.",
        "B2B marketing manager with 8 years of experience in demand generation, content, and lifecycle programs. Led an integrated campaign that generated $2.1M in qualified pipeline while reducing paid acquisition cost by 24%.",
        ["Campaign strategy", "Demand generation", "Content strategy", "Lifecycle marketing", "Marketing analytics", "Positioning", "Budget management", "Team leadership"],
        ["Audience insight", "Commercial contribution", "Channel judgment", "Team leadership"],
        [("Demand", "qualified pipeline, leads, or conversion"), ("Efficiency", "CAC, CPL, ROI, or budget variance"), ("Engagement", "retention, email response, or organic growth")],
        ["Launched an integrated campaign that generated $2.1M in qualified pipeline.", "Reduced paid acquisition cost by 24% through creative and audience testing.", "Built a quarterly content program with sales and subject-matter experts.", "Reworked lifecycle messaging and increased trial-to-paid conversion by 11%."],
        ["Reporting impressions without business context", "Treating every channel as a core skill", "Using brand language instead of clear results", "Leaving budget or team scope unstated"],
        "Platform certificates can support channel expertise, but recent campaign evidence matters more. Add a portfolio link for strategy, creative, or content work only when it is current and easy to review.",
        ["template-009", "template-012", "template-007"],
    ),
    "sales-representative": role(
        "Marketing and Sales", "Sales Representative",
        "A sales resume should make quota performance, territory, deal type, and sales motion immediately visible. Use attainment and account outcomes instead of relying on persuasive adjectives.",
        "Mid-market sales representative with 5 years of B2B SaaS experience across prospecting, discovery, and expansion. Finished at 124% of annual quota and grew twelve existing accounts through needs-led proposals.",
        ["Prospecting", "Discovery", "Negotiation", "Pipeline management", "CRM", "Forecasting", "Account growth", "Product demonstrations"],
        ["Quota record", "Pipeline quality", "Customer discovery", "Account growth"],
        [("Attainment", "quota percentage or ranking"), ("Pipeline", "qualified value, conversion, or cycle length"), ("Accounts", "retention, expansion, or new logos")],
        ["Finished at 124% of annual quota across a mid-market territory.", "Created a discovery framework that raised qualified opportunity rate by 16%.", "Expanded twelve existing accounts through needs-led proposals.", "Built $3.4M in qualified pipeline through targeted outbound sequences."],
        ["Calling yourself a top performer without evidence", "Omitting quota, segment, or territory", "Listing CRM administration as the main result", "Including confidential customer names without approval"],
        "Industry licenses matter in insurance, real estate, financial services, and regulated sales. Put active licenses near the contact section and include sales training only when it is recognized or requested.",
        ["template-011", "template-012", "template-020"],
    ),
    "administrative-assistant": role(
        "Administration and Operations", "Administrative Assistant",
        "An administrative assistant resume should show organization, judgment, confidentiality, and the volume of work coordinated. Replace broad support duties with the calendars, travel, records, and workflows you improved.",
        "Administrative assistant with 6 years of experience supporting multi-site leadership teams. Coordinated calendars across three time zones and introduced a travel workflow that reduced booking changes by 27%.",
        ["Calendar management", "Travel coordination", "Meeting support", "Document control", "Office operations", "Expense processing", "Microsoft 365", "Confidentiality"],
        ["Organization", "Professional judgment", "Service reliability", "Confidentiality"],
        [("Volume", "leaders, meetings, trips, or requests handled"), ("Efficiency", "time saved or rework reduced"), ("Accuracy", "records maintained or errors prevented")],
        ["Coordinated complex calendars for four leaders across three time zones.", "Introduced a travel workflow that reduced booking changes by 27%.", "Organized board materials and maintained accurate confidential records.", "Standardized purchase requests and cut approval follow-up by six hours per week."],
        ["Saying responsible for every routine task", "Leaving the number of stakeholders unclear", "Overemphasizing basic software knowledge", "Using confidential details as proof"],
        "Training in office administration, bookkeeping, or sector systems can help. Experienced assistants should give more space to scope, discretion, and workflow improvements than to general coursework.",
        ["template-004", "template-025", "template-018"],
    ),
    "customer-service": role(
        "Customer Service", "Customer Service Representative",
        "A customer service resume should show case volume, quality, customer outcomes, and calm problem solving. Explain the channels and products you supported and how you improved resolution.",
        "Customer service representative with 4 years of omnichannel support experience in subscription products. Maintained 96% customer satisfaction across more than 1,500 cases and created content that reduced repeat questions by 14%.",
        ["Customer support", "Case management", "De-escalation", "Product knowledge", "CRM", "Quality assurance", "Knowledge bases", "Team coaching"],
        ["Customer outcomes", "Resolution quality", "Product knowledge", "Composure"],
        [("Quality", "CSAT, QA score, or first-contact resolution"), ("Volume", "cases, contacts, or channels supported"), ("Efficiency", "response time, handle time, or repeat contact")],
        ["Maintained a 96% satisfaction score across more than 1,500 cases.", "Created help-center content that reduced repeat questions by 14%.", "Coached six new representatives on de-escalation and case documentation.", "Partnered with product teams to resolve a recurring billing issue affecting 320 customers."],
        ["Using friendly and people person as proof", "No service volume or channel context", "Focusing only on speed and not quality", "Describing angry customers in unprofessional terms"],
        "Product, language, or regulated-industry training can be useful. Keep unrelated certificates brief and prioritize service metrics and problem-solving examples.",
        ["template-004", "template-012", "template-032"],
    ),
    "graphic-designer": role(
        "Creative", "Graphic Designer",
        "A graphic designer resume must work with a portfolio. Use the resume to explain your design role, system thinking, production scope, and collaboration; let the portfolio show the finished craft.",
        "Graphic designer with 6 years of experience building campaign and brand systems across digital and print. Created reusable components that cut production time by 30% and supported launches in nine markets.",
        ["Visual design", "Brand systems", "Typography", "Art direction", "Adobe Creative Suite", "Figma", "Production design", "Creative collaboration"],
        ["Portfolio quality", "Design systems", "Production fluency", "Creative collaboration"],
        [("Efficiency", "production time or revision rounds"), ("Scale", "markets, assets, channels, or launches"), ("Performance", "conversion, engagement, or adoption when attributable")],
        ["Created a modular campaign system used across nine markets.", "Cut production time by 30% by building reusable design components.", "Partnered with marketing to refresh a product launch across web and print.", "Directed vendor production for 120 assets while maintaining brand consistency."],
        ["A decorative resume that is hard to scan", "Portfolio links without project context", "Listing software instead of design decisions", "Claiming campaign performance you cannot attribute"],
        "Place a direct portfolio link with the contact details. A design degree can help early on, but recent, well-explained work and strong fundamentals should dominate the page.",
        ["template-002", "template-009", "template-053"],
    ),
    "teacher": role(
        "Education", "Teacher",
        "A teacher resume should show subject and grade expertise, learning outcomes, classroom practice, and contribution to the school community. Use student evidence carefully and never expose private information.",
        "Middle school teacher with 7 years of experience in literacy instruction, assessment, and differentiated learning. Improved grade-level reading proficiency by 18 percentage points and led a team-wide intervention plan.",
        ["Curriculum planning", "Classroom management", "Assessment", "Differentiated instruction", "Family communication", "Learning technology", "Student support", "Team leadership"],
        ["Instructional practice", "Student growth", "Classroom culture", "Community contribution"],
        [("Learning", "growth, proficiency, or completion rates"), ("Reach", "students, classes, or programs served"), ("Contribution", "curriculum, mentoring, clubs, or team leadership")],
        ["Improved grade-level reading proficiency by 18 percentage points.", "Designed differentiated lessons for a class of thirty-two learners.", "Led a teaching team that aligned assessment and intervention plans.", "Introduced weekly family updates and increased conference participation by 22%."],
        ["Listing duties every teacher performs", "Using student data without context or privacy", "Omitting grade, subject, or curriculum", "A skills section made only of personality traits"],
        "State your active teaching license, endorsements, subjects, and jurisdictions clearly. Put student teaching and practicum experience in the work section when applying for a first role.",
        ["template-013", "template-004", "template-025"],
    ),
    "nurse": role(
        "Healthcare", "Registered Nurse",
        "A registered nurse resume should make licensure, specialty, patient population, clinical skills, and safety record easy to verify. Use operational measures without disclosing protected patient information.",
        "Registered nurse with 5 years of acute medical-surgical experience and active state licensure. Coordinates care for up to six patients per shift and improved discharge education compliance through a standardized checklist.",
        ["Clinical assessment", "Patient care", "Medication administration", "Care coordination", "Patient education", "EHR documentation", "Infection prevention", "Precepting"],
        ["Clinical judgment", "Patient safety", "Specialty experience", "Team communication"],
        [("Care scope", "patient ratio, acuity, beds, or shift type"), ("Quality", "compliance, falls, readmissions, or education completion"), ("Leadership", "new nurses trained or improvement work led")],
        ["Coordinated safe care for up to six acute patients per shift.", "Improved discharge education compliance through a standardized checklist.", "Precepted eight new nurses on unit procedures and documentation.", "Joined a falls-prevention review that reduced unit incidents over two quarters."],
        ["Hiding license status below the work history", "Listing every clinical task without specialty context", "Including identifiable patient details", "Using percentages without explaining the quality measure"],
        "Place RN licensure, state, and expiration status near the top. Add BLS, ACLS, PALS, specialty certification, and compact status when current and relevant to the unit.",
        ["template-029", "template-004", "template-018"],
    ),
    "executive-assistant": role(
        "Administration and Operations", "Executive Assistant",
        "An executive assistant resume should demonstrate prioritization, discretion, executive communication, and operational leverage. Show how you protected leadership time and kept consequential work moving.",
        "Executive assistant with 9 years of experience supporting C-suite leaders and boards in fast-moving organizations. Managed priorities for three executives and coordinated board cycles, leadership events, and confidential follow-up.",
        ["Executive support", "Complex scheduling", "Board coordination", "Travel", "Events", "Executive communication", "Operational judgment", "Confidentiality"],
        ["Executive leverage", "Discretion", "Anticipation", "Operational follow-through"],
        [("Scope", "executives, boards, locations, or time zones"), ("Time", "hours protected or conflicts reduced"), ("Operations", "events, budgets, or action items delivered")],
        ["Managed priorities and scheduling for a CEO and two senior executives.", "Coordinated quarterly board meetings, materials, and follow-up actions.", "Planned a 180-person leadership event within budget and timeline.", "Introduced briefing notes that reduced meeting preparation time by four hours weekly."],
        ["A task list that looks identical to an admin role", "No evidence of discretion or judgment", "Naming confidential board topics", "Overstating authority for executive decisions"],
        "Formal qualifications are secondary to trust and scope for experienced executive assistants. Include governance, project, or event credentials only when they strengthen the target role.",
        ["template-006", "template-015", "template-023"],
    ),
    "student-internship": role(
        "Early Career", "Student and Internship",
        "A student resume should translate coursework, projects, campus work, and part-time experience into evidence of useful skills. Relevance and specificity matter more than having a long work history.",
        "Computer science student seeking a software internship, with project experience in Python, databases, and accessible web interfaces. Built a team prototype, analyzed user feedback, and presented recommendations to faculty reviewers.",
        ["Relevant coursework", "Projects", "Research", "Communication", "Teamwork", "Problem solving", "Digital tools", "Learning agility"],
        ["Relevant projects", "Evidence of learning", "Contribution", "Clear target"],
        [("Project", "users, records, features, or tests completed"), ("Academic", "award, scholarship, or relevant result"), ("Leadership", "participants, volunteers, or funds coordinated")],
        ["Analyzed survey data for a capstone project and presented recommendations.", "Coordinated a student event attended by 240 participants.", "Built a working prototype with a four-person interdisciplinary team.", "Balanced fifteen weekly work hours with a full academic course load."],
        ["An objective that says only what you want", "Unexplained course codes", "Soft skills with no project evidence", "Padding the page with high-school details after they stop being relevant"],
        "Put education near the top and include expected graduation date, relevant coursework, projects, honors, and GPA only when helpful. Use projects as experience when they show real decisions and deliverables.",
        ["template-036", "template-046", "template-057"],
    ),
    "engineering": role(
        "Engineering and Construction", "Engineer",
        "An engineering resume should connect analysis and design work with requirements, testing, manufacturability, safety, quality, or cost. State your discipline and avoid letting software names replace engineering decisions.",
        "Mechanical engineer with 6 years of experience in product design, verification, and supplier changes. Redesigned a critical assembly to reduce failure rate by 23% and cut component lead time by eleven days.",
        ["Engineering design", "Technical analysis", "Verification", "CAD", "Quality", "Root cause analysis", "Requirements", "Cross-functional delivery"],
        ["Technical judgment", "Verification evidence", "Design ownership", "Safety and quality"],
        [("Performance", "failure rate, tolerance, weight, or efficiency"), ("Delivery", "lead time, test cycle, or release timing"), ("Cost", "unit cost, scrap, tooling, or warranty impact")],
        ["Redesigned a critical assembly and reduced unit failure rate by 23%.", "Planned verification testing across eighteen operating conditions.", "Coordinated manufacturing and supplier changes that cut lead time by eleven days.", "Resolved a tolerance stack issue before tooling release and avoided rework."],
        ["A generic engineer title with no discipline", "CAD tools listed without design outcomes", "No verification or requirements context", "Disclosing controlled technical information"],
        "List PE, EIT, chartered status, safety training, and discipline-specific licenses accurately. Early-career engineers can include a compact projects section with constraints, analysis, and test results.",
        ["template-029", "template-021", "template-018"],
    ),
    "medical-assistant": role(
        "Healthcare", "Medical Assistant",
        "A medical assistant resume should balance patient-facing care with accurate clinical and administrative work. Make certification, setting, procedures, scheduling volume, and EHR experience visible.",
        "Certified medical assistant with 4 years of experience in a high-volume family practice. Supported up to 32 patient visits daily while maintaining accurate intake, medication reconciliation, and follow-up documentation.",
        ["Patient intake", "Vital signs", "Medication reconciliation", "Phlebotomy", "EHR documentation", "Scheduling", "Infection control", "Patient communication"],
        ["Patient care", "Clinical accuracy", "Workflow reliability", "Communication"],
        [("Volume", "patient visits, calls, or providers supported"), ("Quality", "documentation, follow-up, or compliance rate"), ("Flow", "wait time, room turnover, or scheduling accuracy")],
        ["Completed intake and documentation for up to 32 patient visits per day.", "Introduced a follow-up queue that raised referral completion by 18%.", "Prepared rooms and supplies while maintaining infection-control standards.", "Trained three new assistants on EHR workflows and patient communication."],
        ["Leaving certification status unclear", "Listing procedures you are not authorized to perform", "Omitting the clinical setting", "Including protected patient information"],
        "State active CMA, RMA, CCMA, CPR/BLS, phlebotomy, and state-required credentials near the top. Match procedure language to your verified training and local scope.",
        ["template-029", "template-004", "template-025"],
    ),
    "warehouse-worker": role(
        "Logistics and Transportation", "Warehouse Worker",
        "A warehouse resume should show safety, accuracy, throughput, equipment, and reliability. Name the operation and shift environment, then quantify orders, inventory, or error reduction where possible.",
        "Warehouse associate with 5 years of experience in e-commerce fulfillment and inventory control. Picked and packed up to 180 orders per shift while maintaining 99.7% scan accuracy and a consistent safety record.",
        ["Picking and packing", "Inventory control", "RF scanners", "Forklift operation", "Shipping and receiving", "Cycle counts", "Safety", "Team coordination"],
        ["Safety", "Accuracy", "Throughput", "Reliability"],
        [("Throughput", "orders, lines, pallets, or units per shift"), ("Accuracy", "scan, inventory, or shipment accuracy"), ("Safety", "incident-free time, audits, or training")],
        ["Picked and packed up to 180 orders per shift with 99.7% scan accuracy.", "Completed cycle counts that corrected 240 inventory discrepancies.", "Trained eight seasonal associates on scanner and packing procedures.", "Reorganized a fast-moving zone and reduced average travel time per order."],
        ["Only saying able to lift a stated weight", "No equipment or warehouse-system detail", "Speed claims without accuracy or safety", "Listing an expired equipment certification as active"],
        "List current forklift, powered industrial truck, OSHA, hazardous-material, or first-aid training when relevant. Keep license status and dates accurate.",
        ["template-004", "template-032", "template-018"],
    ),
    "truck-driver": role(
        "Logistics and Transportation", "Truck Driver",
        "A truck driver resume should make license class, endorsements, equipment, route type, safety, and delivery record immediately clear. Use mileage and service measures without exaggeration.",
        "Class A CDL driver with 7 years of regional and over-the-road experience. Logged more than 650,000 safe miles, maintained 98% on-time delivery, and handled dry van and refrigerated freight.",
        ["Class A CDL", "DOT compliance", "Pre-trip inspection", "ELD", "Route planning", "Freight documentation", "Customer delivery", "Vehicle care"],
        ["Safety record", "License fit", "Delivery reliability", "Equipment experience"],
        [("Safety", "safe miles, preventable incidents, or inspection record"), ("Service", "on-time delivery or claims rate"), ("Scope", "route type, regions, equipment, or freight")],
        ["Logged more than 650,000 safe miles across regional and OTR routes.", "Maintained 98% on-time delivery for refrigerated freight.", "Passed roadside and company inspections with no out-of-service violations.", "Improved route sequencing and reduced weekly idle time by five hours."],
        ["Omitting license class or endorsements", "Safety claims with no time or mileage context", "Not naming equipment and freight type", "Leaving unexplained gaps in driving history"],
        "Place CDL class, issuing state, medical card status, and endorsements near the top. Include tanker, hazmat, doubles/triples, passenger, or TWIC credentials only when current.",
        ["template-004", "template-018", "template-032"],
    ),
    "electrician": role(
        "Skilled Trades", "Electrician",
        "An electrician resume should show license level, systems, environments, code knowledge, troubleshooting, and safety. Describe project scale and the electrical work you personally completed.",
        "Licensed journeyman electrician with 8 years of commercial construction and service experience. Installed and tested distribution systems on projects up to 200,000 square feet while maintaining a strong safety record.",
        ["Electrical installation", "Troubleshooting", "Blueprint reading", "NEC", "Conduit bending", "Panels", "Preventive maintenance", "Lockout/tagout"],
        ["License and code knowledge", "Safe workmanship", "Troubleshooting", "Project experience"],
        [("Scale", "square feet, circuits, panels, or project value"), ("Reliability", "downtime reduced or calls resolved"), ("Safety", "training, audits, or incident-free hours")],
        ["Installed and tested distribution systems for a 200,000-square-foot facility.", "Diagnosed a recurring controls fault and reduced line downtime by 14 hours monthly.", "Led daily safety planning for a five-person electrical crew.", "Completed service documentation and code corrections across 38 tenant spaces."],
        ["Hiding license level or jurisdiction", "Listing tools without systems experience", "No safety or code evidence", "Claiming supervisory work you did not own"],
        "State apprentice, journeyman, master, or contractor license and jurisdiction clearly. Add OSHA, NFPA 70E, low-voltage, lift, or manufacturer training when current and relevant.",
        ["template-021", "template-004", "template-018"],
    ),
    "restaurant-server": role(
        "Hospitality", "Restaurant Server",
        "A restaurant server resume should show service style, guest volume, sales, menu knowledge, teamwork, and reliability. Name the restaurant environment so the reader understands pace and expectations.",
        "Restaurant server with 4 years of experience in high-volume casual and upscale dining. Managed sections of up to ten tables, maintained accurate orders, and increased average check value through informed recommendations.",
        ["Guest service", "POS systems", "Menu knowledge", "Upselling", "Order accuracy", "Food safety", "Cash handling", "Teamwork"],
        ["Guest experience", "Accuracy under pressure", "Sales judgment", "Team reliability"],
        [("Volume", "covers, tables, or sales per shift"), ("Service", "guest feedback, repeat business, or error rate"), ("Sales", "average check, specials, or beverage contribution")],
        ["Managed a ten-table section during weekend services of more than 300 covers.", "Increased average check value through informed beverage and menu recommendations.", "Maintained accurate POS orders and balanced cash at every shift close.", "Trained six new servers on service standards, allergens, and side work."],
        ["Describing friendliness without service evidence", "No indication of restaurant type or pace", "Ignoring food safety and allergen knowledge", "Adding tip income as a performance claim"],
        "List current food-handler, alcohol-service, allergen, or responsible-service certification when required locally. Language skills can be useful when stated accurately.",
        ["template-012", "template-004", "template-032"],
    ),
    "construction-project-manager": role(
        "Engineering and Construction", "Construction Project Manager",
        "A construction project manager resume should establish project type, value, delivery method, safety, schedule, cost, and stakeholder control. Make the scale visible in the first half of the page.",
        "Construction project manager with 10 years of commercial building experience across ground-up and renovation work. Delivered projects up to $28M while controlling schedule, change orders, subcontractors, and owner communication.",
        ["Construction planning", "Scheduling", "Cost control", "Subcontractor management", "Change orders", "Safety", "RFIs and submittals", "Owner reporting"],
        ["Project scale", "Cost and schedule control", "Field coordination", "Safety leadership"],
        [("Scale", "project value, area, trades, or duration"), ("Cost", "variance, savings, or change-order recovery"), ("Schedule", "days saved, milestones, or delay avoided")],
        ["Delivered a $28M occupied renovation within the approved completion window.", "Recovered six weeks through resequencing and subcontractor coordination.", "Negotiated change-order documentation that protected $420K in project value.", "Led weekly safety and logistics planning across twelve active trades."],
        ["Project names without size or delivery context", "No distinction between field and office ownership", "Ignoring safety and change control", "Taking sole credit for team delivery"],
        "List PMP, CCM, OSHA, LEED, first-aid, and contractor licenses when active and relevant. Software such as Procore or Primavera should appear with the work it supported.",
        ["template-016", "template-013", "template-011"],
    ),
    "business-analyst": role(
        "Technology", "Business Analyst",
        "A business analyst resume should show how you turned an unclear business problem into requirements, process changes, or a decision. Name the stakeholders, systems, analysis method, and operational result.",
        "Business analyst with 6 years of experience improving insurance and financial-service workflows. Translated stakeholder needs into system requirements and redesigned a claims process that reduced average handling time by 21%.",
        ["Requirements gathering", "Process mapping", "Stakeholder interviews", "Data analysis", "SQL", "User stories", "UAT", "Change management"],
        ["Problem definition", "Requirements quality", "Stakeholder alignment", "Operational impact"],
        [("Process", "cycle time, handoffs, rework, or completion rate"), ("Delivery", "requirements accepted, defects avoided, or releases supported"), ("Business", "cost, capacity, compliance, or customer outcome")],
        ["Mapped a claims workflow and reduced average handling time by 21%.", "Converted interviews with twelve stakeholder groups into prioritized system requirements.", "Led UAT across eighty scenarios and resolved critical gaps before release.", "Built an exception report that helped operations recover 340 delayed cases."],
        ["Listing documentation tasks without the business decision", "Using analyst terminology without process context", "No distinction between your work and the project team's", "Claiming savings that were never measured"],
        "CBAP, PMI-PBA, Agile, analytics, and sector credentials can help when relevant. Give implemented requirements and process outcomes more space than certification coursework.",
        ["template-017", "template-029", "template-004"],
    ),
    "cybersecurity-analyst": role(
        "Technology", "Cybersecurity Analyst",
        "A cybersecurity analyst resume should establish the environments you protected, the alerts and risks you investigated, and how your work improved detection, response, or control coverage without exposing sensitive details.",
        "Cybersecurity analyst with 5 years of experience in cloud and enterprise security operations. Improved high-severity alert triage, automated evidence collection, and shortened mean time to contain incidents by 34%.",
        ["SIEM", "Incident response", "Threat analysis", "Vulnerability management", "Cloud security", "Identity and access", "Security controls", "Python"],
        ["Investigative judgment", "Response discipline", "Control knowledge", "Environment scale"],
        [("Response", "time to detect, investigate, contain, or recover"), ("Coverage", "endpoints, accounts, controls, or log sources monitored"), ("Risk", "vulnerabilities closed, false positives reduced, or findings remediated")],
        ["Shortened mean time to contain high-severity incidents by 34%.", "Onboarded fifteen log sources into SIEM detections and improved coverage for privileged activity.", "Automated evidence collection and saved the response team twelve hours per month.", "Prioritized remediation of 180 vulnerabilities using exploitability and asset criticality."],
        ["A long tool list with no investigation example", "Publishing sensitive architecture or incident details", "Treating every alert as an incident", "Using certification acronyms without current status"],
        "List active Security+, CISSP, GIAC, cloud, or vendor certifications accurately. A home lab can support an early-career application when it explains the scenario, method, and learning rather than only naming tools.",
        ["template-029", "template-018", "template-004"],
    ),
    "web-developer": role(
        "Technology", "Web Developer",
        "A web developer resume should connect front-end or back-end work with user experience, accessibility, performance, reliability, and delivery. Link to a focused portfolio or repository only when it is ready to review.",
        "Web developer with 4 years of experience building accessible commerce and content platforms in JavaScript, React, and Node.js. Improved Core Web Vitals and reduced checkout abandonment through performance and interface changes.",
        ["JavaScript", "HTML and CSS", "React", "Node.js", "Web accessibility", "Performance", "APIs", "Testing"],
        ["Shipped web work", "Code quality", "User impact", "Accessibility and performance"],
        [("Performance", "load time, Core Web Vitals, bundle size, or errors"), ("Experience", "conversion, completion, accessibility, or engagement"), ("Delivery", "release frequency, defects, or reusable components")],
        ["Improved largest contentful paint from 4.1 seconds to 2.3 seconds.", "Built an accessible checkout flow that reduced form abandonment by 9%.", "Created reusable components adopted across four product teams.", "Added integration tests that cut repeat checkout regressions by 40%."],
        ["A portfolio of unfinished tutorial projects", "Framework names without shipped outcomes", "Ignoring accessibility and browser support", "Describing team code as solely your own"],
        "A degree is optional for many web roles. Prioritize deployed work, accessible code, and a concise portfolio. Add platform or cloud certificates only when the target role asks for them.",
        ["template-029", "template-009", "template-018"],
    ),
    "ux-designer": role(
        "Creative", "UX Designer",
        "A UX designer resume should complement the portfolio by explaining the user problem, research, constraints, collaboration, and outcome. Show how evidence changed the design rather than presenting screens as the whole process.",
        "UX designer with 6 years of experience in B2B software and service design. Combined interviews, analytics, and usability testing to simplify onboarding and improve first-week task completion by 19%.",
        ["User research", "Interaction design", "Prototyping", "Usability testing", "Information architecture", "Design systems", "Figma", "Product collaboration"],
        ["Problem framing", "Research quality", "Interaction craft", "Product impact"],
        [("Usability", "task success, completion time, or error rate"), ("Product", "activation, adoption, retention, or support volume"), ("Research", "participants, studies, themes, or decisions informed")],
        ["Redesigned onboarding and improved first-week task completion by 19%.", "Planned usability studies with 24 customers across three user segments.", "Contributed accessible patterns to a design system used by six squads.", "Mapped a service journey that exposed two high-volume support failure points."],
        ["A visual portfolio with no problem or outcome", "Calling every activity design thinking", "Listing Figma as the main qualification", "Claiming product metrics without attribution"],
        "Place a direct portfolio link with contact details. Education in design, psychology, HCI, or research can add context, but recent case studies and sound judgment should lead.",
        ["template-002", "template-053", "template-009"],
    ),
    "human-resources-manager": role(
        "Human Resources", "Human Resources Manager",
        "An HR manager resume should show the employee population, business context, programs owned, and how your judgment affected retention, manager capability, compliance, or workforce operations.",
        "Human resources manager with 9 years of experience supporting multi-site organizations through growth and change. Led manager development and retention initiatives for a 650-employee workforce, reducing regrettable turnover by 14%.",
        ["Employee relations", "Talent management", "Performance management", "HR policy", "Workforce planning", "Compliance", "HRIS", "Manager coaching"],
        ["Business partnership", "Employee relations judgment", "Program ownership", "Workforce impact"],
        [("Workforce", "employees, locations, managers, or countries supported"), ("People", "retention, engagement, internal mobility, or time to productivity"), ("Operations", "case time, compliance, HRIS accuracy, or process adoption")],
        ["Reduced regrettable turnover by 14% across a 650-employee workforce.", "Coached 45 managers through performance and employee-relations decisions.", "Standardized onboarding across five locations and shortened time to productivity.", "Led an HRIS data review that corrected 1,200 employee records before migration."],
        ["Using people person as the main qualification", "Discussing confidential employee cases", "No indication of workforce size or business context", "Listing policies without showing adoption or outcome"],
        "List SHRM, HRCI, CIPD, or local employment-practice credentials when active. State jurisdictional experience carefully and avoid implying legal authority you do not hold.",
        ["template-015", "template-013", "template-004"],
    ),
    "recruiter": role(
        "Human Resources", "Recruiter",
        "A recruiter resume should make hiring volume, role mix, sourcing strategy, candidate experience, and partnership with hiring managers visible. Balance speed metrics with quality and retention.",
        "Corporate recruiter with 6 years of experience hiring technical and commercial teams. Filled 74 roles in one year, improved qualified interview conversion, and reduced median time to fill by eleven days.",
        ["Full-cycle recruiting", "Sourcing", "Interview design", "Candidate experience", "ATS", "Talent analytics", "Offer management", "Hiring-manager partnership"],
        ["Hiring quality", "Search strategy", "Stakeholder partnership", "Candidate experience"],
        [("Delivery", "roles filled, time to fill, or offer acceptance"), ("Funnel", "qualified conversion, source mix, or pass-through rate"), ("Quality", "retention, hiring-manager satisfaction, or candidate feedback")],
        ["Filled 74 technical and commercial roles while reducing median time to fill by eleven days.", "Built a sourcing strategy that doubled qualified interviews for hard-to-fill engineering roles.", "Raised offer acceptance from 78% to 91% through earlier expectation alignment.", "Trained 38 hiring managers on structured interviews and consistent scorecards."],
        ["Reporting outreach volume as the main achievement", "Speed metrics with no quality context", "No indication of role level or hiring market", "Sharing private candidate or compensation details"],
        "Recruiting certifications can support specialized work, but hiring evidence matters more. Include language, technical-market, executive-search, or regulated-industry expertise when it is relevant and accurate.",
        ["template-011", "template-004", "template-025"],
    ),
    "operations-manager": role(
        "Administration and Operations", "Operations Manager",
        "An operations manager resume should show the process, team, locations, service level, and financial or quality result you controlled. Make the operating environment clear before listing improvement methods.",
        "Operations manager with 10 years of experience leading multi-site service teams. Managed 85 employees across four locations and redesigned staffing and quality routines to improve on-time completion by 16%.",
        ["Operations planning", "Team leadership", "Process improvement", "Budget management", "Quality control", "Capacity planning", "Vendor management", "Performance reporting"],
        ["Operating control", "People leadership", "Process judgment", "Service performance"],
        [("Service", "on-time rate, throughput, backlog, or response time"), ("People", "team size, retention, training, or productivity"), ("Financial", "budget, cost per unit, waste, or savings")],
        ["Improved on-time completion by 16% across four service locations.", "Managed an 85-person team and introduced frontline coaching routines.", "Reduced overtime expense by 12% through demand-based staffing.", "Renegotiated vendor service levels and recovered 320 hours of annual capacity."],
        ["Calling every task strategic", "No team, budget, or location scale", "Cost savings without the operating change", "Listing Lean terms without an applied example"],
        "Lean, Six Sigma, safety, project, or sector credentials can help when backed by operating results. Place licenses near the top when the role requires them.",
        ["template-016", "template-011", "template-013"],
    ),
    "office-manager": role(
        "Administration and Operations", "Office Manager",
        "An office manager resume should demonstrate reliable facilities, vendors, records, purchasing, employee support, and problem solving. Quantify the office size, request volume, or budget you coordinated.",
        "Office manager with 7 years of experience supporting growing professional-services teams. Managed facilities, vendors, purchasing, and onboarding for a 120-person office while reducing supply and service costs by 13%.",
        ["Office operations", "Facilities coordination", "Vendor management", "Purchasing", "Onboarding", "Records management", "Event coordination", "Budget tracking"],
        ["Operational reliability", "Vendor control", "Employee service", "Organization"],
        [("Scope", "employees, locations, vendors, or requests supported"), ("Cost", "budget, savings, or avoided fees"), ("Service", "response time, uptime, satisfaction, or issue resolution")],
        ["Managed facilities and workplace support for a 120-person office.", "Consolidated suppliers and reduced annual service costs by 13%.", "Created an onboarding checklist that eliminated missed access requests.", "Coordinated an office relocation with no interruption to client service."],
        ["A list of errands without operational responsibility", "No size, budget, or vendor context", "Overemphasizing basic calendar software", "Including building-security details"],
        "Facilities, safety, bookkeeping, or office-administration training can be useful. Keep software certificates brief and prioritize evidence of reliable operations.",
        ["template-004", "template-025", "template-018"],
    ),
    "bookkeeper": role(
        "Finance", "Bookkeeper",
        "A bookkeeper resume should show transaction volume, account scope, reconciliation accuracy, payroll or invoicing responsibilities, and the accounting systems you used. Emphasize dependable records and timely close support.",
        "Bookkeeper with 8 years of experience supporting small businesses and professional-service firms. Reconciled multi-account ledgers, processed payroll for 95 employees, and reduced overdue receivables by 22%.",
        ["Accounts payable", "Accounts receivable", "Bank reconciliation", "Payroll", "General ledger", "Invoicing", "QuickBooks", "Financial records"],
        ["Record accuracy", "Transaction scope", "Deadline reliability", "Client service"],
        [("Volume", "transactions, invoices, accounts, or employees processed"), ("Accuracy", "reconciliation variance, corrections, or error rate"), ("Cash flow", "days outstanding, collections, or payment timing")],
        ["Reconciled twelve bank and credit accounts with no unresolved month-end variances.", "Processed biweekly payroll and deductions for 95 employees.", "Introduced receivables follow-up that reduced overdue balances by 22%.", "Prepared organized year-end files that shortened accountant review by two days."],
        ["Saying detail oriented without accuracy evidence", "No indication of transaction volume", "Confusing bookkeeping with certified accounting work", "Listing access to sensitive records without control context"],
        "QuickBooks, Xero, payroll, bookkeeping, or local tax certificates can help. Describe your scope accurately and do not imply CPA or licensed-accountant status unless held.",
        ["template-013", "template-004", "template-018"],
    ),
    "paralegal": role(
        "Legal", "Paralegal",
        "A paralegal resume should establish practice area, matter volume, drafting and research work, filing knowledge, deadline control, and confidentiality. Avoid revealing privileged or identifiable client information.",
        "Paralegal with 6 years of experience supporting commercial litigation and employment matters. Managed active case calendars, prepared discovery materials, and improved filing review controls across a 75-matter caseload.",
        ["Legal research", "Document drafting", "Discovery", "Case management", "Court filing", "Citation", "Deadline tracking", "Confidentiality"],
        ["Legal accuracy", "Deadline control", "Practice-area fit", "Confidential judgment"],
        [("Caseload", "active matters, filings, attorneys, or jurisdictions supported"), ("Quality", "filing acceptance, review errors, or deadline compliance"), ("Efficiency", "review time, retrieval time, or document volume")],
        ["Maintained deadlines and records across a 75-matter litigation caseload.", "Prepared and quality-checked discovery productions exceeding 40,000 documents.", "Created a filing checklist that eliminated repeat court-rejection issues.", "Researched statutes and case law for attorney review across three jurisdictions."],
        ["Disclosing client names or privileged facts", "Claiming legal advice or attorney authority", "No practice-area or jurisdiction context", "Listing software instead of legal work"],
        "List a paralegal certificate, degree, notary commission, e-discovery training, and jurisdiction-specific qualifications when current. Use careful language that reflects work performed under attorney supervision.",
        ["template-013", "template-006", "template-018"],
    ),
    "certified-nursing-assistant": role(
        "Healthcare", "Certified Nursing Assistant",
        "A CNA resume should show active certification, care setting, patient population, daily care scope, observation, documentation, and dependable teamwork. Protect patient privacy in every example.",
        "Certified nursing assistant with 5 years of long-term care and rehabilitation experience. Supported daily living needs for up to twelve residents per shift while maintaining accurate documentation and responsive safety reporting.",
        ["Activities of daily living", "Vital signs", "Mobility assistance", "Patient observation", "Infection prevention", "Documentation", "Dementia care", "Team communication"],
        ["Compassionate care", "Safety awareness", "Reliable observation", "Team support"],
        [("Care scope", "residents, patients, shifts, or units supported"), ("Quality", "documentation, rounding, or care-plan compliance"), ("Reliability", "attendance, shifts covered, or new aides trained")],
        ["Supported activities of daily living for up to twelve residents per shift.", "Reported condition changes promptly and documented care in the facility record.", "Followed transfer and infection-prevention procedures across rehabilitation assignments.", "Helped orient five new aides to unit routines and resident preferences."],
        ["Leaving certification status unclear", "Using only caring and compassionate as evidence", "Listing tasks outside authorized scope", "Including patient names or medical details"],
        "Place active CNA certification, issuing state, registry status, BLS/CPR, and relevant training near the top. Include expiration dates when local employers expect them.",
        ["template-029", "template-004", "template-025"],
    ),
    "dental-assistant": role(
        "Healthcare", "Dental Assistant",
        "A dental assistant resume should show credentials, procedures supported, patient flow, sterilization, imaging, records, and chairside communication. Match every duty to local scope-of-practice rules.",
        "Certified dental assistant with 4 years of general and restorative practice experience. Supported two dentists, maintained instrument-processing standards, and helped improve daily schedule completion across a busy clinic.",
        ["Chairside assisting", "Instrument sterilization", "Dental radiography", "Patient preparation", "Dental records", "Impressions", "Scheduling", "Infection control"],
        ["Clinical readiness", "Infection control", "Patient communication", "Practice flow"],
        [("Volume", "patients, providers, rooms, or procedures supported"), ("Quality", "sterilization compliance, records, or retake rate"), ("Flow", "room turnover, schedule completion, or wait time")],
        ["Provided chairside support for two dentists across restorative and preventive procedures.", "Maintained sterilization logs and instrument processing with complete audit compliance.", "Prepared patients and records for an average of 28 daily appointments.", "Reorganized room setup and reduced between-patient turnover by six minutes."],
        ["Claiming expanded functions without credentials", "No practice type or procedure context", "Ignoring sterilization and patient communication", "Including patient-identifying details"],
        "List CDA, RDA, radiography, coronal polishing, CPR/BLS, and state-required permits when active. Use the exact title and expanded functions recognized in your jurisdiction.",
        ["template-029", "template-004", "template-025"],
    ),
    "pharmacist": role(
        "Healthcare", "Pharmacist",
        "A pharmacist resume should make licensure, practice setting, prescription volume, clinical services, medication safety, and team leadership easy to evaluate. Use quality measures without exposing patient information.",
        "Licensed pharmacist with 8 years of community and ambulatory-care experience. Oversaw up to 420 prescriptions daily, expanded immunization services, and introduced verification checks that reduced dispensing near misses.",
        ["Medication therapy", "Prescription verification", "Patient counseling", "Immunization", "Drug utilization review", "Inventory control", "Pharmacy systems", "Team leadership"],
        ["Medication safety", "Clinical judgment", "Practice scope", "Operational leadership"],
        [("Volume", "prescriptions, patients, vaccinations, or locations supported"), ("Safety", "near misses, interventions, or verification compliance"), ("Service", "wait time, adherence, clinical uptake, or patient access")],
        ["Verified up to 420 prescriptions daily while maintaining safety and counseling standards.", "Expanded seasonal immunization capacity by 35% through appointment and staffing changes.", "Introduced a high-risk medication check that reduced repeat near-miss patterns.", "Resolved insurance and therapy issues with prescribers to prevent treatment delays."],
        ["Hiding license status or jurisdictions", "A prescription volume with no safety context", "Claiming clinical services outside your authority", "Including protected patient information"],
        "Place pharmacist licenses, jurisdictions, immunization authority, controlled-substance registration, and active board certifications near the top. State residency and specialty training accurately.",
        ["template-029", "template-013", "template-018"],
    ),
    "physical-therapist": role(
        "Healthcare", "Physical Therapist",
        "A physical therapist resume should show licensure, setting, patient population, assessment and treatment expertise, caseload, functional outcomes, and collaboration without disclosing patient identities.",
        "Licensed physical therapist with 7 years of outpatient orthopedic experience. Managed a varied caseload, improved plan-of-care completion, and helped patients progress toward measurable mobility and return-to-activity goals.",
        ["Functional assessment", "Therapeutic exercise", "Manual therapy", "Care planning", "Patient education", "Outcome measures", "Documentation", "Interdisciplinary care"],
        ["Clinical reasoning", "Functional outcomes", "Patient education", "Caseload management"],
        [("Outcome", "mobility, pain, function, or plan completion"), ("Caseload", "visits, patients, diagnoses, or settings"), ("Quality", "documentation, attendance, satisfaction, or discharge planning")],
        ["Managed 55 weekly outpatient visits across orthopedic and post-operative conditions.", "Introduced goal reviews that improved plan-of-care completion by 13%.", "Used standardized measures to track mobility and functional progress.", "Mentored three new therapists on documentation and patient education standards."],
        ["Vague claims that every patient improved", "No setting or patient-population context", "Listing techniques without clinical reasoning", "Including identifiable case information"],
        "Place active PT licensure and jurisdictions near the top. Add DPT, residency, board specialization, CPR/BLS, and technique certifications when current and relevant to the setting.",
        ["template-029", "template-004", "template-018"],
    ),
    "retail-sales-associate": role(
        "Retail", "Retail Sales Associate",
        "A retail sales associate resume should show store type, customer volume, product knowledge, sales contribution, transaction accuracy, merchandising, and dependability. Use team-aware metrics rather than claiming all store revenue.",
        "Retail sales associate with 4 years of experience in high-volume apparel and specialty stores. Consistently met individual goals, maintained accurate transactions, and used product knowledge to improve basket value and repeat visits.",
        ["Customer service", "Product knowledge", "POS systems", "Consultative selling", "Merchandising", "Cash handling", "Inventory", "Loss prevention"],
        ["Customer connection", "Sales contribution", "Transaction accuracy", "Store reliability"],
        [("Sales", "goal attainment, units per transaction, or basket value"), ("Service", "customer feedback, loyalty enrollment, or returns resolved"), ("Operations", "transaction accuracy, inventory, or merchandising volume")],
        ["Achieved 108% of individual sales goals across two consecutive quarters.", "Used fit and product knowledge to increase average units per transaction.", "Balanced POS activity accurately across opening and closing shifts.", "Reset seasonal merchandising across a 6,000-square-foot sales floor."],
        ["Calling yourself a people person without evidence", "Taking credit for all store revenue", "No product category or store-volume context", "Ignoring accuracy, inventory, and loss prevention"],
        "Product training, language skills, responsible-sales permits, or loss-prevention training can help when relevant. Keep unrelated coursework brief.",
        ["template-012", "template-004", "template-032"],
    ),
    "chef": role(
        "Hospitality", "Chef",
        "A chef resume should identify cuisine, service format, covers, station or kitchen leadership, menu development, food cost, safety, and quality. The scale and style of the operation should be immediately clear.",
        "Chef with 10 years of experience in high-volume contemporary restaurants and hotel banquets. Led a twelve-person brigade, delivered services of up to 450 covers, and reduced food cost through menu and purchasing changes.",
        ["Menu development", "Kitchen leadership", "Food preparation", "Cost control", "Purchasing", "Food safety", "Inventory", "Training"],
        ["Culinary standard", "Service execution", "Cost control", "Team leadership"],
        [("Service", "covers, events, stations, or outlets supported"), ("Cost", "food cost, waste, yield, or purchasing savings"), ("People", "brigade size, training, retention, or promotion")],
        ["Led a twelve-person brigade through services of up to 450 covers.", "Reduced food cost by 2.8 percentage points through menu and purchasing changes.", "Created seasonal dishes using local suppliers and documented consistent yields.", "Raised food-safety audit performance through station checks and coaching."],
        ["A dish list with no kitchen or service context", "Calling recipes proprietary in place of evidence", "No cost, sanitation, or leadership information", "Using awards that cannot be verified"],
        "List culinary education, food-manager certification, allergen training, responsible-service credentials, and apprenticeships when current. A portfolio can support specialized pastry or presentation work.",
        ["template-012", "template-009", "template-004"],
    ),
    "plumber": role(
        "Skilled Trades", "Plumber",
        "A plumber resume should show license level, residential or commercial setting, systems installed or repaired, code knowledge, diagnostics, project scale, and safe work practices.",
        "Licensed journeyman plumber with 9 years of commercial service and construction experience. Installed and commissioned water and drainage systems, resolved complex service calls, and coordinated work across occupied facilities.",
        ["Plumbing installation", "Diagnostics", "Blueprint reading", "Code compliance", "Pipefitting", "Fixture repair", "Preventive maintenance", "Jobsite safety"],
        ["License and code fit", "Diagnostic ability", "Quality workmanship", "Customer and site care"],
        [("Scale", "fixtures, units, buildings, or project value"), ("Service", "calls completed, first-time fix, or response time"), ("Reliability", "callbacks, leaks prevented, downtime, or inspections passed")],
        ["Installed domestic water and drainage systems across a 140-unit development.", "Diagnosed recurring pressure loss and prevented further tenant outages.", "Completed service documentation and code repairs across 45 commercial sites.", "Coordinated shutdowns in an occupied hospital wing without unplanned disruption."],
        ["Leaving license level or jurisdiction unclear", "Listing tools instead of systems and outcomes", "No code, inspection, or safety context", "Claiming work completed by the whole trade crew"],
        "State apprentice, journeyman, master, gas, backflow, or contractor credentials and jurisdictions accurately. Add OSHA, confined-space, medical-gas, or equipment training when relevant.",
        ["template-021", "template-004", "template-018"],
    ),
    "hvac-technician": role(
        "Skilled Trades", "HVAC Technician",
        "An HVAC technician resume should name the systems, refrigerants, building types, controls, service volume, diagnostic work, energy results, and safety credentials relevant to the target employer.",
        "HVAC technician with 7 years of commercial service experience across rooftop units, split systems, boilers, and building controls. Improved first-visit resolution and reduced repeat calls through structured diagnostics.",
        ["HVAC diagnostics", "Preventive maintenance", "Refrigeration", "Electrical troubleshooting", "Building controls", "Air balancing", "Customer service", "Safety"],
        ["Diagnostic depth", "System experience", "Service reliability", "Safe compliance"],
        [("Service", "calls, first-time fix, callbacks, or response time"), ("Equipment", "tonnage, units, sites, or system types"), ("Efficiency", "energy, runtime, downtime, or maintenance completion")],
        ["Raised first-visit resolution to 87% across commercial service calls.", "Maintained HVAC systems at 32 retail and office locations.", "Diagnosed a controls fault that reduced repeated comfort complaints.", "Completed preventive-maintenance routes with accurate readings and follow-up recommendations."],
        ["No EPA or license status", "A parts list without diagnostic reasoning", "Mixing residential and commercial claims without context", "Omitting electrical and safety practices"],
        "Place EPA Section 608, state licenses, NATE, OSHA, refrigerant, controls, and manufacturer certifications near the top when current and relevant.",
        ["template-021", "template-004", "template-018"],
    ),
    "automotive-technician": role(
        "Skilled Trades", "Automotive Technician",
        "An automotive technician resume should show vehicle or equipment specialization, diagnostics, repair quality, productivity, customer documentation, tools and certifications. Focus on verified repairs rather than a generic parts list.",
        "Automotive technician with 8 years of dealership and independent-shop experience. Diagnoses electrical and drivability concerns, completes complex repairs, and maintains strong quality-control and comeback performance.",
        ["Vehicle diagnostics", "Electrical systems", "Engine repair", "Brake systems", "Scan tools", "Preventive maintenance", "Repair documentation", "Shop safety"],
        ["Diagnostic reasoning", "Repair quality", "Technical range", "Productivity"],
        [("Quality", "comeback rate, first-time repair, or inspection accuracy"), ("Productivity", "flagged hours, repair orders, or cycle time"), ("Scope", "vehicle brands, systems, fleet size, or certifications")],
        ["Maintained a low comeback rate across electrical and drivability repairs.", "Used scan data and circuit testing to resolve intermittent starting faults.", "Completed digital inspections that improved estimate clarity for customers.", "Mentored two apprentices on diagnostic process and shop safety."],
        ["Listing every hand tool", "Parts replacement without diagnostic evidence", "No indication of vehicle specialization", "Stating ASE certification without current status"],
        "List active ASE areas, manufacturer training, state inspection, emissions, hybrid/EV, refrigerant, and commercial-license credentials precisely.",
        ["template-021", "template-004", "template-032"],
    ),
    "delivery-driver": role(
        "Logistics and Transportation", "Delivery Driver",
        "A delivery driver resume should show vehicle type, route size, stop volume, safety, on-time service, proof-of-delivery accuracy, customer care, and any required license or medical credentials.",
        "Delivery driver with 6 years of last-mile and commercial-route experience. Completed up to 145 daily stops, maintained a strong safety record, and improved route consistency through careful sequencing and customer communication.",
        ["Route planning", "Safe driving", "Vehicle inspection", "Proof of delivery", "Package handling", "Customer service", "Navigation", "Delivery documentation"],
        ["Safety record", "On-time reliability", "Route efficiency", "Customer care"],
        [("Route", "stops, miles, service area, or packages per shift"), ("Service", "on-time rate, delivery success, or customer feedback"), ("Safety", "incident-free mileage, inspections, or compliance")],
        ["Completed up to 145 daily stops while maintaining accurate proof of delivery.", "Maintained an incident-free record across more than 180,000 route miles.", "Resequenced a dense route and reduced average completion time by 35 minutes.", "Resolved delivery exceptions through timely customer and dispatcher communication."],
        ["A valid license claim with no class or status", "Speed metrics without safety and accuracy", "No vehicle or route context", "Leaving preventable incidents unexplained"],
        "Place driver's license class, endorsements, medical card, DOT, defensive-driving, and equipment credentials near the top when required. Keep status and dates accurate.",
        ["template-004", "template-018", "template-032"],
    ),
}
